apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "http"}}}'
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: http
      protocol: TCP
  selector:
    name: cubeartisan
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      name: cubeartisan
  template:
    metadata:
      labels:
        name: cubeartisan
    spec:
      containers:
        - name: cubeartisan
          image: "ghcr.io/cubeartisan/cubeartisan:latest"
          imagePullPolicy: Always
          env:
            - name: DISCORD_URL
              value: "https://discord.gg/NKCaZRFU"
            - name: DOWNTIME_ACTIVE
              value: "false"
            - name: ELASTIC_APM_ACTIVE
              value: 'true'
            - name: ELASTIC_APM_CLOUD_PROVIDER
              value: none
            - name: ELASTIC_APM_ENVIRONMENT
              value: "<ENV>"
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: ELASTIC_APM_SECRET_TOKEN
            - name: ELASTIC_APM_TRANSACTION_IGNORE_URLS
              value: ""
            - name: ELASTIC_APM_SERVER_URL
              value: "http://apm.kube-logging.svc:8200/"
            - name: ELASTIC_APM_SERVICE_NAME
              value: CubeArtisan
            - name: ELASTIC_APM_SERVICE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: cubeartisan-version
                  key: TAG
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: ELASTICSEARCH_PASSWORD
            - name: ELASTICSEARCH_URL
              value: "https://elasticsearch-es-http.kube-logging.svc:9200/"
            - name: ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: ELASTICSEARCH_USER
            - name: EMAIL_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_PASSWORD
            - name: EMAIL_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_USERNAME
            - name: FLASKROOT
              value: "http://cubeartisan-recommender"
            - name: LISTEN_ADDR
              value: "0.0.0.0"
            - name: MONGODB_DBNAME
              value: "cubeartisan"
            - name: MONGODB_HOST
              value: "mongo-svc"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-password
                  key: password
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLICASET
              value: mongo
            - name: MONGODB_USER
              value: cubeartisan
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: SESSION
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: SESSION
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: SESSION_SECRET
            - name: SITE_HOSTNAME
              value: <ENV>
            - name: SITE_NAME
              value: CubeArtisan
            - name: SITE_ROOT
              value: https://<ENV>
            - name: SITE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: cubeartisan-version
                  key: TAG
            - name: SOURCE_REPO
              value: https://github.com/CubeArtisan/cubeartisan
            - name: SUPPORT_EMAIL
              value: support@cubeartisan.net
            - name: SUPPORT_EMAIL_FROM
              value: CubeArtisan Support Team <support@cubeartisan.net>
          ports:
            - containerPort: 5000
              name: http
          resources:
            limits:
              memory: 4Gi
              cpu: 1000m
              ephemeral-storage: 4Gi
            requests:
              memory: 4Gi
              cpu: 1000m
              ephemeral-storage: 4Gi
          livenessProbe:
            httpGet:
              path: /version
              port: http
            failureThreshold: 1
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /version
              port: http
            initialDelaySeconds: 180
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /version
              port: http
            failureThreshold: 40
            periodSeconds: 15
      restartPolicy: Always
      imagePullSecrets:
        - name: github-docker