apiVersion: v1
kind: Service
metadata:
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    name: cubeartisan
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  selector:
    matchLabels:
      name: cubeartisan
  template:
    metadata:
      labels:
        name: cubeartisan
    spec:
      containers:
        - image: "ghcr.io/cubeartisan/cubeartisan:<TAG>"
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: TCG_PLAYER_PRIVATE_KEY
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: TCG_PLAYER_PRIVATE_KEY
            - name: TCG_PLAYER_PUBLIC_KEY
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: TCG_PLAYER_PUBLIC_KEY
            - name: SESSION_SECRET
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: SESSION_SECRET
            - name: DBNAME
              value: "cubeartisan"
            - name: SESSION
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: SESSION
            - name: EMAIL_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_USERNAME
            - name: EMAIL_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_PASSWORD
            - name: FLASKROOT
              value: "http://cubeartisan-recommender"
            - name: PORT
              value: "5000"
            - name: SITE_VERSION
              value: "<TAG>"
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200/"
            - name: ELASTIC_APM_SERVICE_NAME
              value: CubeArtisan_beta
            - name: ELASTIC_APM_SERVER_URL
              value: "http://apm-server:8200/"
            - name: ELASTIC_APM_SERVICE_VERSION
              value: "<TAG>"
            - name: ELASTIC_APM_ACTIVE
              value: 'true'
            - name: ELASTIC_APM_ENVIRONMENT
              value: "<ENV>"
            - name: ELASTIC_APM_TRANSACTION_IGNORE_URLS
              value: "/version"
            - name: MONGODB_URL
              value: "mongodb://mongo:27017/cubeartisan?replicaSet=rs0"
            - name: LISTEN_ADDR
              value: "0.0.0.0"
            - name: SITE_ROOT
              value: "https://<ENV>"
            - name: SITE_NAME
              value: CubeArtisan (beta)
            - name: SUPPORT_EMAIL_FROM
              value: CubeArtisan Support Team <support@cubeartisan.net>
            - name: SUPPORT_EMAIL
              value: support@cubeartisan.net
            - name: DOWNTIME_ACTIVE
              value: "false"
            - name: DISCORD_URL
              value: "https://discord.gg/NKCaZRFU"
            - name: SOURCE_REPO
              value: https://github.com/CubeArtisan/cubeartisan
          name: cubeartisan
          ports:
            - containerPort: 5000
              name: cubeartisan
          resources:
            limits:
              memory: 2Gi
              cpu: 1500m
              ephemeral-storage: 2Gi
            requests:
              memory: 2Gi
              cpu: 1500m
              ephemeral-storage: 2Gi
          readinessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /version
              port: 5000
            failureThreshold: 30
            periodSeconds: 15
      restartPolicy: Always
      imagePullSecrets:
        - name: github-docker
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cubeartisan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cubeartisan
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50