apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cubeartisan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cubeartisan
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 65