apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cubeartisan
resources:
- 51-tls-certificate.kube.yaml
- ../per_env
- 42-horizontal-auto-scaling.kube.yaml
- 70-velero.kube.yaml
- 72-cubeartisan-backup.kube.yaml
images:
- name: ghcr.io/cubeartisan/cubeartisan
  newTag: v1.0.0-rc0-3
patchesStrategicMerge:
- environment-override.yaml
patchesJson6902:
- path: ingress.patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: cubeartisan-ingress
    version: v1
