kind: Namespace
apiVersion: v1
metadata:
  name: kube-logging
---
kind: Namespace
apiVersion: v1
metadata:
  name: cubeartisan
---
kind: Namespace
apiVersion: v1
metadata:
  name: cubeartisan-staging
---
kind: Namespace
apiVersion: v1
metadata:
  name: cubeartisan-ingress
---
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: cubeartisan
  name: config-connector