apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: kube-logging
  name: kibana
spec:
  version: 7.14.0-SNAPSHOT
  count: 1
  http:
    service:
      metadata:
        annotations:
          cloud.google.com/neg: '{ "ingress": true}'
          cloud.google.com/app-protocols: '{"https":"HTTPS"}'
      spec:
        type: NodePort
  elasticsearchRef:
    name: elasticsearch
    namespace: kube-logging
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            limits:
              memory: 3Gi
              cpu: 1000m
            requests:
              memory: 3Gi
              cpu: 200m
  config:
    xpack.fleet.agents.elasticsearch.host: https://elasticsearch-es-http.kube-logging.svc:9200
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.kube-logging.svc:8220"]
    server.publicBaseUrl: https://kibana.cubeartisan.net