apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 51-tls-certificate.kube.yaml
- ../per_env
namespace: cubeartisan-staging
images:
- name: ghcr.io/cubeartisan/cubeartisan
  newTag: 7361596d
patchesStrategicMerge:
- environment-override.yaml
patchesJson6902:
- path: ingress.patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: cubeartisan-ingress
    version: v1