apiVersion: v1
kind: Service
metadata:
  labels:
    service: cubeartisan-recommender
  name: cubeartisan-recommender
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    service: cubeartisan-recommender
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: cubeartisan-recommender
  name: cubeartisan-recommender
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: cubeartisan-recommender
  template:
    metadata:
      labels:
        service: cubeartisan-recommender
    spec:
      containers:
        - name: cubeartisan-recommender
          image: docker.pkg.github.com/cubeartisan/cubecuberecommender/cubecobrarecommender:90f8c141
          ports:
          - containerPort: 8000
          command: [/bin/sh, -c]
          args:
            - gunicorn web:app --bind=0.0.0.0
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}